export const restaurants = [
    {
        srno: 1,
        name: "The Urban Spoon",
        image: "/res/restaurant1.jpg",
        cuisine: "Italian, Chinese",
        rating: 4.5,
        location: "Sadar, Nagpur",
    },
    {
        srno: 2,
        name: "Barbeque Nation",
        image: "/res/restaurant2.jpg",
        cuisine: "BBQ, North Indian",
        rating: 4.2,
        location: "Wardha Road, Nagpur",
    },
    {
        srno: 3,
        name: "Haldiram's",
        image: "/res/restaurant3.jpg",
        cuisine: "Indian Sweets, Fast Food",
        rating: 4.8,
        location: "Sitabuldi, Nagpur",
    },
    {
        srno: 4,
        name: "Little Italy",
        image: "/res/restaurant4.jpg",
        cuisine: "Italian",
        rating: 4.3,
        location: "Dharampeth, Nagpur",
    },
    {
        srno: 5,
        name: "Le Cafe",
        image: "/res/restaurant5.jpg",
        cuisine: "Cafe, Continental",
        rating: 4.6,
        location: "Civil Lines, Nagpur",
    },
    {
        srno: 6,
        name: "Biryani House",
        image: "/res/restaurant6.jpg",
        cuisine: "Biryani, Mughlai",
        rating: 4.7,
        location: "Ramdaspeth, Nagpur",
    },
    {
        srno: 7,
        name: "The Breakfast Story",
        image: "/res/restaurant7.jpg",
        cuisine: "Breakfast, Cafe",
        rating: 4.4,
        location: "West High Court Road, Nagpur",
    },
    {
        srno: 8,
        name: "Pind Tadka",
        image: "/res/restaurant8.jpg",
        cuisine: "Punjabi, North Indian",
        rating: 4.5,
        location: "Manish Nagar, Nagpur",
    },
    {
        srno: 9,
        name: "Cream Stone",
        image: "/res/restaurant9.jpg",
        cuisine: "Ice Cream, Desserts",
        rating: 4.3,
        location: "Gokulpeth, Nagpur",
    },
    {
        srno: 10,
        name: "Zayka",
        image: "/res/restaurant10.jpg",
        cuisine: "Indian, Chinese",
        rating: 4.6,
        location: "Laxmi Nagar, Nagpur",
    },
];

export default restaurants;
